# Generated by Django 5.0.6 on 2024-06-21 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id_genero', models.AutoField(db_column='idGenero', primary_key=True, serialize=False)),
                ('genero', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido_M', models.CharField(max_length=20)),
                ('apellido_P', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=45)),
                ('direccion', models.CharField(blank=True, max_length=50, null=True)),
                ('id_genero', models.ForeignKey(db_column='id_Genero', on_delete=django.db.models.deletion.CASCADE, to='bike.genero')),
            ],
            options={
                'ordering': ['rut'],
            },
        ),
    ]
